### ISSUE TITLE
Poreikio valdymas

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#1020]
### Užduotys

- [ ] Koordinatorius ir tvarkytojas neturi galėti redaguoti Poreikio [#1008](https://github.com/atviriduomenys/katalogas/issues/1008)
- [x] https://github.com/atviriduomenys/katalogas/issues/998
- [ ] Tvarkytojas Koordinatorius Institucija ryšys [#1033](https://github.com/atviriduomenys/katalogas/issues/1033)
- [ ] Poreikių forma [#403](https://github.com/atviriduomenys/katalogas/issues/403)
- [ ] Kodėl Poreikių filtre "Duomenų rinkinio būsena" reikšmė - nepriskirti? [#1036](https://github.com/atviriduomenys/katalogas/issues/1036)
- [ ] https://github.com/atviriduomenys/katalogas/issues/984
- [ ] Įgyvendinti automatinį Poreikio būklių valdymą [#86](https://github.com/atviriduomenys/prieziura/issues/86)
- [ ] Koordinatoriaus prenumeratos [#1031](https://github.com/atviriduomenys/katalogas/issues/1031)
- [ ] Poreikio būsenų sąrašas #1012
- [ ] Įgyvendinti poreikio tiražavimą [#104](https://github.com/atviriduomenys/prieziura/issues/104)
- [ ] Rodyti poreikio el. pašto adresą tvarkytojui [#961](https://github.com/atviriduomenys/katalogas/issues/961)
- [ ] Poreikio atoriaus el.paštas
[#1002](https://github.com/atviriduomenys/katalogas/issues/1002)
- [ ] Informavimas apie pateiktą poreikį
[#992](https://github.com/atviriduomenys/katalogas/issues/992)
- [ ] Klaida poreikio organizacijų sąraše [#684](https://github.com/atviriduomenys/katalogas/issues/684)
- [ ]
