### ISSUE TITLE
Duomenų rinkinai formos filtrų sutvarkymas

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#1023]
1. Viešoje versijoje prisijungusiems ir neprisijungusiems vartotojams nerodomi tik Nepublikuojami rinkiniai ir pats **Nepublikuojami** filtro Rinkinio būsenos pasirinkimas. 
2. Kol kas funkcijos Mano rinkiniai ir Mano organizacijos rinkiniai nerodomos visiems (jų nešalinant nes jos tikriausiai tos pačios, kurios prieinamos per individualios paskyros sąrašą)

3. Pakeisti filtro pasirinkimą **Nepriskirta** į **Nepublikuojama**

Vyr. koordinatoriui rodoma:

- **Nepublikuojami** filtro Rinkinio būsenos pasirinkimas
- Pasirinkus **Nepublikuojami** rodomi visi nepublikuojami, visų organizacijų duomenų rinkiniai (kiti viešai matomi nerodomi)

Ministerijos koordinatoriui rodoma:
- **Nepublikuojami** filtro Rinkinio būsenos pasirinkimas
- Pasirinkus **Nepublikuojami** rodomi visi nepublikuojami ministerijos kompetencijos srityje esančių organizacijų duomenų rinkiniai (kiti viešai matomi nerodomi)

Organizacijos koordinatoriui rodoma:
- **Nepublikuojami** filtro Rinkinio būsenos pasirinkimas
- Pasirinkus **Nepublikuojami** rodomi visi nepublikuojami organizacijos duomenų rinkiniai (kiti viešai matomi nerodomi)

Organizacijos tvarkytojui rodoma:
- **Nepublikuojami** filtro Rinkinio būsenos pasirinkimas
- Pasirinkus **Nepublikuojami** rodomi visi nepublikuojami tvarkytojui priskirti duomenų rinkiniai (kiti viešai matomi nerodomi)

4. **Brandos lygis** filtre papildomai pridėti antrą tik kitokio atspalvio (pilką) trijų žvaigždučių eilutę pasirinkimą: 

![Image](https://github.com/atviriduomenys/katalogas/assets/69783864/fd8bc67d-8011-4919-aaf4-6877cf79c329)
kuris skaičiuojamas pagal turinčius distribuciją duomenų rinkinius, atvertus atviraisiais formatais (su prierašu prie žvaigždučių "atviri formatai"). 
- [ ] Suapvalinti brandos lygio rodomą reikšmę [#883](https://github.com/atviriduomenys/katalogas/issues/883)

5. **Valdymo sritis** filtro pavadinimą pakeisti į Valdymo/veiklos sritis ir patį filtrą pateikti po Organizacijos filtru.
Valdymo/Veiklos srities filtrą papildyti pasirinkimo reikšmėmis  
- [x] Valdymo sričių duomenų neatitikimų pašalinimas [#96](https://github.com/atviriduomenys/prieziura/issues/96)
Valdymo sričių sąrašą turėtų būti galima tvarkyti vyr. koordinatoriui administravimo aplinkoje
 - [x] Ministerijų dubliavimas [#1017](https://github.com/atviriduomenys/katalogas/issues/1017)
6. Organizacijų filtre sutvarkyti organizacijos paieškos veikimą

- [x] Neveikia filtras [#1039](https://github.com/atviriduomenys/katalogas/issues/1039)
7. Filtrą Grupė pakelti lange iš karto po Brandos lygio filtru

**Comment by Grigorjeva11** [comment]
Prašau patikslinti, ar dar aktualu. Jeigu aktualu, pažymėkite prioritetą (P0 - aukščiausias).

**Comment by Grigorjeva11** [comment]
Prašau patikslinti, ar dar aktualu. Jeigu aktualu, pažymėkite prioritetą (P0 - aukščiausias).
