### ISSUE TITLE
Supaprastinta duomenų rinkinio forma

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#13]
- [x] Turi būti galimybė duomenų rinkinius redaguoti ne administravimo aplinkoje, o viešojoje dalyje, duomenų rinkinio peržiūros puslapyje, paspaudus mygtuką „Keisti“. Mygtukas „Keisti“ turi būti rodomas tik rinkinio administravimo teisę turintiems naudotojams.

Šiuo metu, duomenų rinkinio formoje yra 6 kortelės:

1. Inventorinimo duomenys
2. Struktūra
3. Prioritetai
4. Finansiniai duomenys
5. Metaduomenys
6. Duomenys

- [x] Vietoj šių kortelių reikėtų palikti vieną formą, kurioje būtų galima keisti visus metaduomenis.

- [x] Duomenų struktūros dalis turi būti [sujungta su distribucijų dalimi](https://github.com/atviriduomenys/katalogas/issues/14). Duomenų struktūros failai turi būti įkeliame ne kaip failai, o importuojamas kaip distribucijų sąrašas.

- [x] Duomenų dalis (arba distribucijų administravimas) turėtu būti iškeltas atskirai į [duomenų rinkinių peržiūros puslapyje esantį distribucijų sąrašą](https://github.com/atviriduomenys/katalogas/issues/14).

- [x] Prioritetų dalis naikinam ir keičiamai paklausos vertinimus, kuris [skaičiuojamas automatiškai](https://github.com/atviriduomenys/katalogas/issues/9).

- [x] Finansiniai duomenys perkeliami į atvėrimo finansavimų sąrašą.

- [x] Metaduomenys perkeliame į pagrindinę duomenų rinkinio formą, paliekant tik tuos formos laukus, kuriuos galima redaguoti. Visi kiti laukai, kuriuose rodoma tik informacija, perkeliami į duomenų rinkinio peržiūros dalį.
