### ISSUE TITLE
Koordinatorių ir tvarkytojų migracija

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#171]
Modifikuotas Representative modelis, padaryta duomenų migracija, perkeliant esamus duomenų rinkinio koordinatorius ir tvarkytojus, o taip pat organizacijos koordinatorius ir tvarkytojus į Representative lentelę.
Įgyvendinta can_manage(user, object) service funkcija, kuri patikrina ar user (koordinatorius, tvarkytojas) gali tvarkyti nurodytą objectą: Organization/Dataset/Representative/Request/DatasetDistribution.

---

Anksčiau ADP naudotojas galėjo priklausyti vienai organizacijai, organizacija galėjo turėti vieną koordinatorių ir kelis tvarkytojus, rinkinys galėjo turėti lygiai vieną koordinatorių ir vieną tvarkytoja.

Dabar situacija keičiasi taip, kad vienas `User`, gali būti įtrauktas į kelias organizacijas, suteikiant jam tam tikrą rolę. Taip pat ir su rinkiniais, vienas `Dataset` gali turėti kelis `User`, su skirtingomis rolėmis.

Siūlau tai įgyvendinti vieno `Representative` modelio pagalba, su generic ryšiais į objektus, kuriuose naudotojas turi kažkokias teises.

Sukūrus (tiksliau perdarius) `Representative` modelį, reikia padaryti duomenų migraciją, kuri perkelia esamus duomenų rinkinio koordinatorius ir tvarkytojus, o taip pat organizacijos koordinatorius ir tvarkytojus į `Representative` lentelę.

Tada reikėtų įgyvendinti `can_manage(user, object)` service funkciją, kuri patikrina ar `user` gali tvarkyti nurodytą `object`. `object` vietoje gali būti perduoti tokie objektai:

- Organization
- Dataset
- Representative
- Request
- DatasetDistribution

Galimos tokios rolės:

- `coordinator` (koordinatorius) - gali būti priskirtas `Organization`, `Dataset` ir `Request` modeliams, gali atlikti visus veiksmus su organizacija, jos rinkiniais, prašymais adresuotais organizacijai, organizacijos ir rinkinio nariais. Organizacijoje gali būti daugiau nei vienas koordinatorius, tam tikri koordinatoriai gali turėti oficialią žymę, t.y. koordinatoriai paskirti įstaigos vadovo ir turintys pasirašytą raštą. Rinkinio arba prašymo koordinatorius, kuris nėra konkretaus rinkinio ar prašymo organizacijos koordinatorius, gali matyti ir tvarkyti tik `Representative` iš organizacijų, kuriose yra koordinatorius, tuo tarpu jei naudotojas yra rinkinio ar prašymo organizacijos koordinatorius, gali tvarkyti visus representatives, net ir ne iš savo organizacijų.
- `manager` (tvarkytojas) - gali būti priskirti prie `Organization`, `Dataset` ir `Request`, minėtuose objektuose gali būti priskirta daugiau nei vienas tvarkytojas, tvarkytojai gali tvarkyti objektus, prie kurių yra paskirti, tvarkytojai negali tvarkyti `Representative`. Organizacijos tvarkytojas, negali tvarkyti pačios organizacijos, tačiau gali tvarkyti visus organizacijai priskirtus rinkinius ir prašymus.
- `user.is_staff` ir `user.is_superuser` gali viską matyti ir tvarkyti, neturint jokios rolės.

Ateityje gali būti pridėta daugiau rolių.

Minėta `can_manage(user, object)` turėtu grąžinti `True` arba `False`, atliekant visus aukščiau aprašytus patikrinimus.

Užduotys:

- [ ] Padaryti migraciją į `Representative`, perkeliant esamus organizacijų, rinkinių ir prašymų koordinatorius ir tvarkytojus į `Representative`, pašalinant nuo organizacijų, rinkinių ir prašymų atitinkamus atributus, paliekant viską tik `Representative` modelyje.
- [ ] Įgyvendinti `can_manage(user, object)` funkciją, manau, kad ji turėti būti `vitrina.orgs.services`.
- [ ] Peržiūrėti ir pataisyti #91.
- [ ] Peržiūrėti ir pataisyti #89.
- [ ] Peržiūrėti ir pataisyti #43.
- [ ] Peržiūrėti ir pataisyti #90.
- [ ] Prie organizacijos ir rinkinio, nuorodą į narių sąrašą turi rodyti tik koordinatoriams.

**Comment by adp-atea** [comment]
Klausimai dėl duomenų migravimo: 
1. Dataset turi laukus manager, coordinator ir representative_id. Manager ir coordiantor rodo į userius, tai kaip suprantu, reikia sukurti Representative objektus su atitinkamai naudotojais ir atitinkamomis rolėmis. Tačiau nelabai aišku, ką reikėtų daryti su representative_id.  Ar tai iš viso naudojamas laukas?
2. Request turi lauką user, čia kaip suprantu irgi reikia sukurti  Representative objektą su susijusiu user? Bet tada kokia turėtų būti rolė? Paimti pagal user.role?
3. Organization prie savęs jokių laukų neturi susijusių su user, tai čia tiesiog jau esančius Representative objektus perdaryti, kad organization duomenys persikeltų į generic ryšio atributus?

**Comment by sirex** [comment]
> 1. Dataset turi laukus manager, coordinator ir representative_id. Manager ir coordiantor rodo į userius, tai kaip suprantu, reikia sukurti Representative objektus su atitinkamai naudotojais ir atitinkamomis rolėmis. Tačiau nelabai aišku, ką reikėtų daryti su representative_id. Ar tai iš viso naudojamas laukas?

`representative_id` nenaudojamas. Galima jį išvis ištrinti.

> 2. Request turi lauką user, čia kaip suprantu irgi reikia sukurti Representative objektą su susijusiu user? Bet tada kokia turėtų būti rolė? Paimti pagal user.role?

`Request.user` yra prašymo atverti duomenis autorius, neturi nieko bendro su `Representative`.

> 3. Organization prie savęs jokių laukų neturi susijusių su user, tai čia tiesiog jau esančius Representative objektus perdaryti, kad organization duomenys persikeltų į generic ryšio atributus?

Taip ir papildomai, visus `User.organization` ir `User.role` perkelti į `Representative`. Tačiau, palikti `User.organization` ir pašalinti `User.role`. `User.organization` turėtu žymėti, kad naudotojas yra iš šios organizacijos, bet jis nebūtinai turi turėti įrašą `Representative` lentelėje, su priskirta role.

**Comment by sirex** [comment]
Dėl teisių tikrinimo `can_manage` funkcijos. Atidžiau peržiūrėjau ir siūlau keisti pavadinimą į `has_perm`, nes šiek tiek keičiasi funkcijos prasmė.

Siūlau naudoti tokį funkcijos protokolą:

```python
from enum import Enum
from typing import Type

from django.db.models import Model

from vitrina.users.models import User


class Action(Enum):
    CREATE = 'create'
    UPDATE = 'update'
    DELETE = 'delete'


def has_perm(
    user: User,            # request.user
    action: Action,
    obj: (
        Model |            # kai action yra update, delete
        Type[Model]        # kai action yra create
    ),
    parent: Model | None = None,  # kai action yra create, objektas ant kurio kuriamas obj
) -> bool:
    ...
```

Naudojimo pavyzdžiai:

```python
has_perm(user, Action.CREATE, Dataset, org)
has_perm(user, Action.UPDATE, dataset)
has_perm(user, Action.DELETE, dataset)
has_perm(user, Action.UPDATE, org)
```

Ateityje bus daugiau `Action` variantų, tokių, kaip publish, status ir pan.

Visais atvejais, kai `isinstance(obj, Type)`, `parent` argumentas tampa privalomas, kitais atvejais, neprivalomas.

**Comment by adp-atea** [comment]
Darant atsirado dar nemažai klausimų:
1.  Kas galės pridėti organizaciją? 
2. Ar Representative modelyje šalinam organization lauką, nes jo reikšmė kaip ir perkeliama į generic lauką?
2.1. Jei nepašalinam, ar šis laukas privalomas? Jei privalomas, kokią reikšmę turėtume suteikti duomenų rinkinių representatives, kurie permigruojami?
2.2. Jei pašalinam, kaip nustatyti, kad duomenų rinkinio representative priklauso tam tikrai organizacijai? Čia dėl šitos dalies "Rinkinio arba prašymo koordinatorius, kuris nėra konkretaus rinkinio ar prašymo organizacijos koordinatorius, gali matyti ir tvarkyti tik Representative iš organizacijų, kuriose yra koordinatorius, tuo tarpu jei naudotojas yra rinkinio ar prašymo organizacijos koordinatorius, gali tvarkyti visus representatives, net ir ne iš savo organizacijų."
3. Kas gali pridėti/redaguoti duomenų rinkinio šaltinį? Ar veiksmas turėtų būti leidžiamas duomenų rinkio arba duomenų rinkinio organizacijos nariams?
4. Kas gali pridėti prašymą? Pagal užduoties aprašymą, atrodo, kad veiksmas turėtų būti leidžiamas organizacijos tvarkytojams ir koordinatoriams, tačiau dabar pridedant prašymą, nei formoje, nei pridėjimo nuorodoje (kaip su duomenų rinkiniu) jokio ryšio su organizacija nėra.
5. Ar neturėtų būti papildomų Action objekto peržiūrai ir sąrašo peržiūrai?
6. Kadangi prie User šalinam rolę, kaip turėtų būti filtruojamos užduotys, rodomos naudotojui prisijungus, jei jos priskirtos tam tikrai rolei? Ar atrenkam Representative objektus pagal naudotoją ir jo organizaciją ir roles gaunam iš jų?

Kiek esu padarius nupushinau ir padariau pull request, jei galėsit pažiūrėkit ar į tą pusę has_perm metodas daromas.

**Comment by sirex** [comment]
> Kas galės pridėti organizaciją?
`user.is_staff` ir `user.is_superuser`.

[Vėliau](https://github.com/atviriduomenys/katalogas/issues/16) organizacijos bus importuojamos iš RC.

> Ar Representative modelyje šalinam organization lauką, nes jo reikšmė kaip ir perkeliama į generic lauką?
Taip šalinam ir padarom migraciją, perkeliant `organization` į `object_content` generic lauką.

> Jei pašalinam, kaip nustatyti, kad duomenų rinkinio representative priklauso tam tikrai organizacijai? Čia dėl šitos dalies "Rinkinio arba prašymo koordinatorius, kuris nėra konkretaus rinkinio ar prašymo organizacijos koordinatorius, gali matyti ir tvarkyti tik Representative iš organizacijų, kuriose yra koordinatorius, tuo tarpu jei naudotojas yra rinkinio ar prašymo organizacijos koordinatorius, gali tvarkyti visus representatives, net ir ne iš savo organizacijų."

Teisės tikrinamos imant konkretų objektą ir visus jo tėvinius objektus. Žiūrėti https://github.com/atviriduomenys/katalogas/pull/201#discussion_r996819570

> Kas gali pridėti/redaguoti duomenų rinkinio šaltinį? Ar veiksmas turėtų būti leidžiamas duomenų rinkio arba duomenų rinkinio organizacijos nariams?

Rinkinio šaltinį gali pridėti rinkinio arba rinkinio organizacijos koordinatorius arba tvarkytojas.

> Kas gali pridėti prašymą? Pagal užduoties aprašymą, atrodo, kad veiksmas turėtų būti leidžiamas organizacijos tvarkytojams ir koordinatoriams, tačiau dabar pridedant prašymą, nei formoje, nei pridėjimo nuorodoje (kaip su duomenų rinkiniu) jokio ryšio su organizacija nėra.

Prašymus gali pateikti visi prisijungę naudotojai.

Prašymai gali būti adresuojami organizacijai, arba konkrečiam rinkiniui arba nenurodant nei organizacijos, nei rinkinio. Jei prašymo formoje nėra galimybės pasirinkti organizacijos, tai čia klaida.

> Ar neturėtų būti papildomų Action objekto peržiūrai ir sąrašo peržiūrai?

Taip, iš esmės reikėtų ir peržiūros veiksmo. Nors visi mato viską, tada tvarkytojai gali matyti ir tai, kas pažymėta `is_publick = False`.

> Kadangi prie User šalinam rolę, kaip turėtų būti filtruojamos užduotys, rodomos naudotojui prisijungus, jei jos priskirtos tam tikrai rolei? Ar atrenkam Representative objektus pagal naudotoją ir jo organizaciją ir roles gaunam iš jų?

Atrenkam pagal `Representative` user ir role.
