### ISSUE TITLE
Duomenų atvėrimo suvestinių parametrų publikavimo aplinkos sukūrimas

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#19]
Turi būti sukurta skelblentė (angl. dashboard), kurioje dinamiškai pateikiami suvestiniai portalo lankomumo, atvertų duomenų rinkinių naudojimo, duomenų rinkinių atvėrimo eigos ir kiti rodikliai.

Šiuo metu, yra galimybė naudotis įvairiomis ataskaitomis, tačiau ataskaitos kuriamos ir atnaujinamos rankiniu būdu, galima pateikti tik atskirus pjūvius, nėra galimybės dinamiškai matyti statistiką įvairiais pjūviais. Nėra vizualizacijos.

Saugyklos duomenų naudojimo žurnalas nėra integruotas į Katalogą.

Duomenų atvėrimo skelblentėje turėtu būti atvaizduojami visi [Duomenų rinkinių atvėrimo stebėsenai reikalingi rodikliai](https://www.e-tar.lt/portal/lt/legalAct/7e1a0120802911eb9601893677bfd7d8), tačiau ne statinių ataskaitų, o interaktyvių vizualizacijų pagalba.

### Užduotys

- [x] https://github.com/atviriduomenys/katalogas/issues/277
- [x] https://github.com/atviriduomenys/katalogas/issues/242
- [x] https://github.com/atviriduomenys/katalogas/issues/278
- [x] https://github.com/atviriduomenys/katalogas/issues/297
- [x] https://github.com/atviriduomenys/katalogas/issues/298
- [x] https://github.com/atviriduomenys/katalogas/issues/299
- [x] https://github.com/atviriduomenys/katalogas/issues/330
- [x] https://github.com/atviriduomenys/katalogas/issues/316
- [ ] https://github.com/atviriduomenys/katalogas/issues/315
- [x] https://github.com/atviriduomenys/katalogas/issues/314
- [x] https://github.com/atviriduomenys/katalogas/issues/313
- [x] https://github.com/atviriduomenys/katalogas/issues/312
- [x] https://github.com/atviriduomenys/katalogas/issues/350

#### Poreikio gauti duomenis filtrai

- [x] https://github.com/atviriduomenys/katalogas/issues/271

### Sprint 4
 
| Užduotis | Numatyta | Sugaišta |
| --- | --- | --- |
| #73 | 8 | - |
| #131 | 2 | - |
| **Viso** | 10 | 10 |
