### ISSUE TITLE
Išoriniai Katalogai

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#22]
Galimybė importuoti ir susieti duomenų rinkinius iš išorinių metaduomenų katalogų.

- Perdaryti Gis-Centro Geoportal katalogo integraciją.
- Perdaryti IRS katalogo integraciją.
- Vilniaus Swagger API metaduomenų integracija.
- Statistikos departamento ArcGis katalogo integracija.
- Finansų ministerijos CKAN katalogo integracija.
- Vilniaus savivaldybės CKAN katalogo integracija.

Matyt geriausias variantas, parengti kiekvieno išorinio metaduomenų katalogo struktūros aprašą, kuriame duomenys būtų transformuojami į vieningą duomenų modelį, o tada importuoti tokius duomenis iš Saugyklos į Katalogą.

### Užduotys

- [x] https://github.com/atviriduomenys/spinta/issues/364
- [x] https://github.com/atviriduomenys/spinta/issues/336
- [x] https://github.com/atviriduomenys/spinta/issues/217
- [x] https://github.com/atviriduomenys/spinta/issues/256
- [ ] #295
- [ ] https://github.com/atviriduomenys/katalogas/issues/71
- [ ] #296 
- [x] https://github.com/atviriduomenys/spinta/issues/89
- [x] https://github.com/atviriduomenys/spinta/issues/98
- [ ] #294
- [x] https://github.com/atviriduomenys/katalogas/issues/1235
- [ ] https://github.com/atviriduomenys/katalogas/issues/343

### Informacija

- https://data.europa.eu/en/academy/data-governance-act-implementation
