### ISSUE TITLE
Duomenų rinkinių atvėrimo planavimo procesas

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#474]
- [x] https://github.com/atviriduomenys/katalogas/issues/494 (ATEA)
- [x] https://github.com/atviriduomenys/katalogas/issues/396 (ATEA)
- [x] https://github.com/atviriduomenys/katalogas/issues/609
- [x] https://github.com/atviriduomenys/katalogas/issues/614
- [x] https://github.com/atviriduomenys/katalogas/issues/610
- [x] https://github.com/atviriduomenys/katalogas/issues/534
- [x] https://github.com/atviriduomenys/katalogas/issues/631
- [x] https://github.com/atviriduomenys/katalogas/issues/632
- [x] https://github.com/atviriduomenys/katalogas/issues/634

**Comment by sirex** [comment]
> Šį planą sudaro tokie duomenys

Planai siejami ne su Rinkiniais, o su Poreikiais. Taip nurodyta teisės aktuose:

> 20. Institucijos ir valstybės valdomi subjektai vykdo duomenų naudojimo bei poreikio stebėseną ir, atsižvelgdami į duomenų vartotojų poreikius, pasiūlymus ir technines galimybes, pildo duomenų rinkinius ir kelia brandos lygį.
-- https://e-seimas.lrs.lt/portal/legalAct/lt/TAD/327dd210495011ebb394e1efb98d3e67/asr

Duomenų naudotojai teikia poreikius ar pasiūlymus, kurie gali būti įvairių formų:

- Poreikis atverti duomenis - duomenų teikėjas priima sprendimą ar tai bus atvertas vienas duomenų rinkinys, keli ar bus papildytas jau atvertas duomenų rinkinys.
- Pasiūlymas keisti duomenų rinkinį - pasiūlymas gali būti susijęs su klaidomis metaduomenyse ar pačiuose duomenyse.
- Pasiūlymas gali būti adresuotas kelioms organizacijoms - kiekviena organizacija atitinkamai atveria arba papildo viena ar kelis savo tvarkomus duomenų rinkinius.

Dėl tos priežasties mano supratimu, plane turėtu atsispindėti ne Rinkiniai, o Poreikiai, nes vienam Duomenų rinkiniui, gali būti pateikta labai daug Poreikių ar pasiūlymų.

Galiausiai, reikia atkreipti dėmesį, kad Poreikiai ateina iš išorės naudotojų, kurie gali teikti besidubliuojančius ar persidengiančius poreikius, kurie gali būti patenkinti vienu kartu arba išskaidyti į atskiras dalis, jei poreikis susijęs su skirtingo sudėtingumo darbas arba jei poreikis adresuotas skirtingoms organizacijoms.

Ko pasekoje, patys Poreikiai yra priskiriami Plano įrašams, kur nurodytas terminas, kada konkretus Poreikis ar jo dalis ar Poreikių grupė bus patenkinti ir kas tai darys.

Turime Planus, kuriuos kuria kiekviena organizacija, kuri tenkina poreikius. Planai rodomi kiekvienos organizacijos puslapyje, pavyzdžiui:

https://test.data.gov.lt/orgs/78/plans/

Kiekviena organizacija, gali įtraukti Poreikį į savo planą ir nustatyti terminą, kada Poreikis bus patenkintas.

Kelios skirtingos organizacijos gali įsitraukti Poreikį į savo planą ir nustatyti skirtingus Poreikio patenkinimo terminus.

Pats savaime Planas yra labiau aktualus kiekvienai Organizacijai.

Tuo tarpu Poreikių ir Pasiūlymų sąraše galima matyti bendrą informaciją apie tai, ar Poreikiai tenkinami ar ne.

Todėl, vietoj atskiro Plano sąrašo, siūlyčiau tobulinti Poreikių sąrašą, kurio filtruose galima įtraukti naują būseną:

- Vėluoja

Būsena „Vėluoja“ būtų taiokoma tiems duomenų rinkiniams, kuriems nebuvo pateiktas joks atsakymas, per 5 darbo dienas, kaip numatyta Duomenų atvėrimo tvarkos apraše.

Taip pat būsena „Vėluoja“ galėtu apimti ir duomenų rinkinius, kurie turi atsakymą, įtraukti į planą, tačiau vėluoja plane numatyti terminai.

Mano supratimu, pats planavimo procesas yra labiau vidinis kiekvienos organizacijos dalykas, o planavimas yra susijęs su Poreikiais, o ne Rinkiniais. Patys Poreikia gali būti susiję su Rinkiais.

Rinkiniai <- Poreikiai -> Planas

> Planuojamo atverti duomenų rinkinio atvėrimo data registruojama duomenų rinkinio registravimo formoje, kurią reikėtų šiek tiek modifikuoti:

Teoriškai, naujo duomenų rinkinio formoje galima įtraukti lauką su data, kada planuojama atverti duomenų rinkinį. Tačiau toks laukas gali būti rodomas tik naujo rinkinio formoje. Sukūrus naują rinkinį, būtų automatiškai sukurtas įrašas organizacijos plane, su nurodyta data.

Dabar tai daroma ne vienoje formoje, o atskirai, planų sąraše:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/919ff396-bcb9-434f-ab1b-2f49efc233a2)

Tokiu būdu atskiriama duomenų rinkinio inventorizacija, nuo atvėrimo planavimo.

Tai iš esmės tokia funkcija yra.

> Tuo atveju, kai planuojama papildyti jau atvertą duomenų rinkinį, ši forma turi leisti pasirinkti rinkinį iš atvertų rinkinių sąrašo, pasinaudojant paieška pagal duomenų rinkinio pavadinimo teksto dalį.

Tokia funkcija taip pat yra. Jei duomenų rinkinys jau atvertas, galima į planą įtraukti papildomus jau atverto duomenų rinkinio tobulinimus ar pakeitimus.

Jei įstaiga modernizuoja informacinę sistemą, kurios metu bus tvarkoma keletas duomenų rinkinių, visi modernizuojami duomenų rinkiniai gali būti įtraukti į vieną Plano įrašą, nurodant vieną terminą, kuris sutampa su modernizavimo projekto pabaiga.

> Atskiros Institucijos aktualus numatytų atverti duomenų rinkinių sąrašas yra matomas administratoriaus administravimo sąsajoje.

Toks sąrašas jau yra, pavyzdžiui:

https://test.data.gov.lt/orgs/78/plans/

Kiekviena institucija turi savo planą. Administratorius ir visi kiti naudotojai mato visų organizacijų planus.

> Bendrą visų viešojo sektoriaus duomenų rinkinių sąrašą, turėtų būti galimybė išsifiltruoti Duomenų rinkinių puslapio Busenos filtre

Bendro visų organizacijų planų sąrašo nėra, nors tokį sąrašą galima nesunkiai padaryti.

Tačiau manau, kad planai negali būti rodomi Rinkinių sąraše, nes Organizacijų Planai ir Rinkiniai yra skirtingi dalykai.

Gal būt čia turima mintyje, kad Rinkinių filter, prie rinkinių būsenos įtraukti naują būseną, „Planuojami atverti“?

- https://github.com/atviriduomenys/katalogas/issues/396

Jei taip, tai tai jau yra nurodyta kitoje užduotyje.

Tikriausiai analogiško filtro reikėtu ir Poreikių filtruose. Nes Planai yra skirti ne tik rinkinių atvėrimui, bet ir Poreikių tenkinimui.

**Comment by JuliusLADP** [comment]
Duomenų atvėrimą planuoja viešas sektorius. Viešojo sektoriaus institucijos poreikių kuriuos registruoja išorės duomenų vartotojai nei planuoja, nei gali tai daryti.  Poreikių planas ir planavimas betiksliai dalykai, nenumatyti jokiais teisės aktais. Teisės akte -- https://e-seimas.lrs.lt/portal/legalAct/lt/TAD/327dd210495011ebb394e1efb98d3e67/asr  yra nustatyta:
- 13.1. Rengia ir publikuoja Portale su institucija ar valstybės valdomu subjektu suderintą **duomenų atvėrimo planą**, kurį sudaro atsižvelgdamas į Portale pateiktus Naudotojų prašymus dėl naujų atvirų duomenų rinkinių gavimo ir (ar) esamų atvirų duomenų rinkinių pakeitimo ir (ar) papildymo.
- į planą sudaro tokie įrašai, kuriuose yra tokie duomenys: Duomenų rinkinio pavadinimas (Naujo rinkinio, Atverto papildymas ir/ar pataisymas), planuojama atvėrimo/papildymo/patikslinimo data; atveriančios atsakingos institucijos pavadinimas, nuoroda į rinkinio metaduomenis kataloge ir nuoroda į poreikio formą. 

visos kitos detalės mano buvo išsamiai aprašytos aukščiau

**Comment by sirex** [comment]
Dabartinis funkcionalumas vienas prie vieno atitinka teisės aktus. Išskyrus antrą pastraipą, kuri nėra teisės akte? Bent jau tokio tekso neradau.

> 13.1. Rengia ir publikuoja Portale su institucija ar valstybės valdomu subjektu suderintą duomenų atvėrimo planą

Būtent taip ir yra įgyvendinta:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/68a4a435-c193-4bf1-a5ec-4cf7a74afecf)
-- https://test.data.gov.lt/orgs/78/plans/

> kurį sudaro atsižvelgdamas į Portale pateiktus Naudotojų prašymus

Būtent taip ir įgyvendinta, Planas rengiamas ne naujų duomenų atvėrimui, o Prašymų tenkinimui, kur gali būti prašoma atverti arba naują rinkinį arba papildyti esamą.

Dabar veikia taip, VDA atsidaro prašymą ir įtraukia į savo Planą:

![image](https://github.com/atviriduomenys/katalogas/assets/297583/14b5888f-289e-46e4-b114-3c22d1ff4ff6)
-- https://test.data.gov.lt/requests/14303/plans/

Mano supratimu, teisės akte nurodyta, kad Planas sudaromas atsižvelgiant į Prašymus. T.y. Planas yra sudaromas Prašymų tenkinimui, kaip tai apibrėžta 9 punkte:

> 9. Pranešimai apie duomenų klaidą (toliau – Pranešimas) ir prašymai dėl naujų atvirų duomenų rinkinių gavimo ir (ar) esamų atvirų duomenų rinkinių papildymo (toliau – Prašymas) nagrinėjami Lietuvos Respublikos viešojo administravimo įstatymo nustatyta tvarka. Pranešimai ir Prašymai, registruoti Portale, turi būti išnagrinėti, klaidos registrų, informacinių sistemų ar elektroninių dokumentų pirminiuose šaltiniuose, kuriuose duomenys registruojami pirmą kartą, (toliau – šaltiniai) turi būti identifikuotos, ištaisytos ir atsakymai Portale pateikiami per 5 darbo dienas nuo Pranešimo ar Prašymo gavimo Portale dienos. Atsakant į Pranešimą informuojama apie duomenų ištaisymą arba atsisakymą ištaisyti duomenis (tokiu atveju paaiškinama, kodėl duomenys negali būti ištaisyti) arba apie ilgesnį terminą, bet ne ilgesnį kaip 3 mėnesiai nuo Pranešimo ar Prašymo gavimo Portale dienos, per kurį klaidos bus ištaisytos. Atsakant į Prašymą nurodoma, ar duomenys gali būti atverti ir kada bus publikuojami Portale. Kai duomenys negali būti atverti, atsakyme nurodoma priežastis, kodėl duomenys negali būti atverti.

**Comment by sirex** [comment]
_(originalus aprašymas)_

Sutvarkyti įvairių rolių dalyvaujančių plano rengimo procese vartotojų sąsjas pagal galiojančiais teisės aktais nustatytas duomenų atvėrimo veiklas. Glaustai pateikiu reikalingo įgyvendinti ADP planavimo proceso aprašymą.

Šį planą sudaro tokie duomenys:

![Image](https://user-images.githubusercontent.com/69783864/262240866-851b43bb-9ffc-40d2-868b-da5e084daef2.png)

Šiuos duomenis registruoja arba tvarko duomenų teikėjų koordinatoriai, institucijai priėmus sprendimą atverti duomenis savo iniciatyva arba pagal ADP registruotą duomenų poreikį. Planuojamo atverti duomenų rinkinio atvėrimo data registruojama duomenų rinkinio registravimo formoje, kurią reikėtų šiek tiek modifikuoti:


![Image](https://user-images.githubusercontent.com/69783864/262351231-64952dfd-d655-440d-9215-f5bc7bf36c75.png)

Tuo atveju, kai planuojama papildyti jau atvertą duomenų rinkinį, ši forma turi leisti pasirinkti rinkinį iš atvertų rinkinių sąrašo, pasinaudojant paieška pagal duomenų rinkinio pavadinimo teksto dalį. 

Atskiros Institucijos aktualus numatytų atverti duomenų rinkinių sąrašas yra matomas administratoriaus administravimo sąsajoje.
Bendrą visų viešojo sektoriaus duomenų rinkinių sąrašą, turėtų būti galimybė išsifiltruoti Duomenų rinkinių puslapio Busenos filtre



ADP turi būti skelbiamas Numatytų atverti duomenų rinkinių planas.

**Comment by JuliusLADP** [comment]
Teiginys, kad "Planai siejami ne su Rinkiniais, o su Poreikiais - yra klaidingas, nes remiamasi ne ta teisės akto citata. Cituojamas punktas apatariamu klausimu nei prie ko:

Institucijos ir valstybės valdomi subjektai vykdo duomenų naudojimo bei poreikio stebėseną ir, atsižvelgdami į duomenų vartotojų poreikius, pasiūlymus ir technines galimybes, pildo duomenų rinkinius ir kelia brandos lygį.
-- https://e-seimas.lrs.lt/portal/legalAct/lt/TAD/327dd210495011ebb394e1efb98d3e67/asr" 
Viešojo sektoriaus institucijos poreikių kuriuos registruoja išorės duomenų vartotojai nei planuoja, nei gali tai daryti. Poreikių planas ir planavimas betiksliai dalykai, nenumatyti jokiais teisės aktais. 

Teisės akte -- https://e-seimas.lrs.lt/portal/legalAct/lt/TAD/327dd210495011ebb394e1efb98d3e67/asr dėl DUOMENŲ RINKINIŲ ATVĖRIMO sakoma:

13.1. Rengia ir publikuoja Portale su institucija ar valstybės valdomu subjektu suderintą duomenų atvėrimo planą, kurį sudaro atsižvelgdamas į Portale pateiktus Naudotojų prašymus dėl naujų atvirų duomenų rinkinių gavimo ir (ar) esamų atvirų duomenų rinkinių pakeitimo ir (ar) papildymo.
Planą sudaro tokie įrašai, kuriuose yra tokie duomenys: Duomenų rinkinio pavadinimas (Naujo rinkinio, Atverto papildymas ir/ar pataisymas), planuojama atvėrimo/papildymo/patikslinimo data; atveriančios atsakingos institucijos pavadinimas, nuoroda į rinkinio metaduomenis kataloge ir nuoroda į poreikio formą.
visos kitos detalės mano buvo išsamiai aprašytos aukščiau

**Comment by Grigorjeva11** [comment]
Prašau patikslinti, ar dar aktualu. Jeigu aktualu, pažymėkite prioritetą (P0 - aukščiausias).
