### ISSUE TITLE
Duomenų pateikimas EDP

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#490]
Kad praeitų testą https://data.europa.eu/mqa/catalogues/data-gov-lt/?locale=en

Priklauso nuo:

- [x] https://github.com/atviriduomenys/spinta/issues/336
- [x] https://github.com/atviriduomenys/spinta/issues/308
- [ ] https://github.com/atviriduomenys/katalogas/issues/295 (IVPK)

Nepatvirtintos užduotys, bet blokuojančios integraciją su EDP:

- [x] https://github.com/atviriduomenys/spinta/issues/289
- [x] https://github.com/atviriduomenys/spinta/issues/161
- [x] https://github.com/atviriduomenys/spinta/issues/96
- [x] https://github.com/atviriduomenys/spinta/issues/204
- [x] https://github.com/atviriduomenys/spinta/issues/512
- [x] https://github.com/atviriduomenys/spinta/issues/397
- [x] https://github.com/atviriduomenys/spinta/issues/379
- [x] https://github.com/atviriduomenys/spinta/issues/380
- [x] Check why validator does not work: https://data.europa.eu/mqa/methodology?locale=en
- [x] https://github.com/atviriduomenys/prieziura/issues/161
- [ ] Issues with [dcat-ap-3](https://github.com/atviriduomenys/katalogas/issues?q=is%3Aopen+is%3Aissue+label%3Adcat-ap-3)

### Nuorodos

- https://dataeuropa.gitlab.io/data-provider-manual/harvesting/
- https://www.w3.org/TR/rdf-syntax-grammar/
- https://semiceu.github.io/DCAT-AP/releases/3.0.0/
- https://semiceu.github.io/uri.semic.eu-generated/DCAT-AP/releases/2.2.0-hvd/

### Validatoriai

- https://www.w3.org/RDF/Validator/
- https://data.europa.eu/mqa/shacl-validator-ui/data-provision
- https://data.europa.eu/api/mqa/shacl/
