### ISSUE TITLE
Geoportalo importas

### ISSUE THREAD

**Issue by JuliusLADP** [atviriduomenys/katalogas#491]
Užduočių reikalingų Geoportal importui schema (schemoje ne visos, o tik pagrindinės užduotys):

![geoportal drawio](https://github.com/atviriduomenys/katalogas/assets/297583/447ed197-25ac-49d4-9b01-3c4d37c99937)

### Laikinas greitesnis sprendimas

- [ ] https://github.com/atviriduomenys/katalogas/issues/1235

### Pirmo prioriteto užduotys

- [x] https://github.com/atviriduomenys/spinta/issues/256
- [x] https://github.com/atviriduomenys/spinta/issues/217
- [x] https://github.com/atviriduomenys/spinta/issues/508
- [x] https://github.com/atviriduomenys/spinta/issues/391
- [x] https://github.com/atviriduomenys/spinta/issues/346
- [x] https://github.com/atviriduomenys/spinta/issues/394
- [x] https://github.com/atviriduomenys/spinta/issues/289
- [x] https://github.com/atviriduomenys/spinta/issues/579
- [x] https://github.com/atviriduomenys/spinta/issues/512
- [ ] https://github.com/atviriduomenys/katalogas/issues/295 (IVPK)
- [ ] https://github.com/atviriduomenys/katalogas/issues/71 (IVPK)
- [x] https://github.com/atviriduomenys/spinta/issues/670
- [x] https://github.com/atviriduomenys/spinta/issues/660
- [ ] https://github.com/atviriduomenys/spinta/issues/661
- [x] https://github.com/atviriduomenys/spinta/issues/663
- [x] https://github.com/atviriduomenys/spinta/issues/664
- [ ] https://github.com/atviriduomenys/spinta/issues/625
- [ ] https://github.com/atviriduomenys/spinta/issues/582
- [ ] https://github.com/atviriduomenys/spinta/issues/583
- [ ] https://github.com/atviriduomenys/spinta/issues/161
- [x] https://github.com/atviriduomenys/spinta/issues/651
- [ ] https://github.com/atviriduomenys/spinta/issues/665
- [ ] https://github.com/atviriduomenys/katalogas/issues/296

- [ ] Geoportal tiesioginis importas #1235 

### Antro prioriteto užduotys

- [ ] https://github.com/atviriduomenys/katalogas/issues/346
- [ ] https://github.com/atviriduomenys/katalogas/issues/343
- [ ] Harvested rinkinių peradresavimas
- [ ] https://github.com/atviriduomenys/katalogas/issues/874

**Comment by ATEAanalyst** [comment]
Reikalingas pristatymas apie norimą pasiekti rezultatą ir darbų aptarimas ir paskirstymas. Pageidautina, kad dalyvautų ir Mantas.
