### ISSUE TITLE
Žodyno modulio sukūrimas (II dalis)

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#51]
### Užduotys

- [ ] https://github.com/atviriduomenys/katalogas/issues/302
- [ ] https://github.com/atviriduomenys/katalogas/issues/290
- [ ] https://github.com/atviriduomenys/katalogas/issues/288
- [ ] https://github.com/atviriduomenys/katalogas/issues/292
- [ ] https://github.com/atviriduomenys/katalogas/issues/293
