### ISSUE TITLE
Žodyno modulio sukūrimas (III dalis)

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/katalogas#52]
### Užduotys

- [x] https://github.com/atviriduomenys/katalogas/issues/327
- [x] https://github.com/atviriduomenys/katalogas/issues/325
- [x] https://github.com/atviriduomenys/katalogas/issues/326
- [x] https://github.com/atviriduomenys/katalogas/issues/333
- [x] https://github.com/atviriduomenys/katalogas/issues/334
- [x] https://github.com/atviriduomenys/katalogas/issues/335
- [x] https://github.com/atviriduomenys/katalogas/issues/336
- [x] https://github.com/atviriduomenys/katalogas/issues/339
- [x] https://github.com/atviriduomenys/katalogas/issues/340
- [x] https://github.com/atviriduomenys/katalogas/issues/342
- [ ] https://github.com/atviriduomenys/katalogas/issues/343
- [x] https://github.com/atviriduomenys/katalogas/issues/344
- [ ] https://github.com/atviriduomenys/katalogas/issues/345
- [ ] https://github.com/atviriduomenys/katalogas/issues/346
